README.md
lib/index.js
lib/oauth.js
test/oauth.js

As mentioned in #40, this is a PR adding the option to force https in redirect_uri.
Granted, it might not be the best solution to alter the request object like this, but this certainly works. The other option would be to pass in the settings as a parameter to the location function, not sure which one you prefer? IMO the naming of the option (force) indicates some force, and thus we are forcing the request object to be https :)
PR also adds a test for this.

Add option for forcing https.

---

lib/oauth.js
test/oauth.js

`redirect_uri` is sent to the provider a second time. This code forces https (if option is set) in that case as well.

Make forceHttps complete 

---

README.md
lib/oauth.js
test/providers.js

As discussed in the issues here: https://github.com/hapijs/bell/issues/49 the pull request has been submitted.

passing back expires_in for oauth 2.0 refresh token request

---

README.md
examples/arcgisonline.js
lib/index.js
lib/providers/arcgisonline.js
lib/providers/index.js
package.json
test/providers.js

Closed #65 and rebased this commit into separate branch for the ease of merging.
Cheers!

Add ArcGIS Online provider

---

README.md
lib/providers/index.js
lib/providers/phabricator.js
test/providers.js

Added support for third party installations of phabricator, the user must supply a URI in the config options in order for it to work.
Closes #75

Support for Phabricator

---

lib/providers/facebook.js
test/oauth.js
test/providers.js

might be a fix for #66 
reference:
- https://developers.facebook.com/docs/apps/upgrading
- https://github.com/jaredhanson/passport-facebook/commit/c5a3fa65685eae74de2b68564da7f3c6c440111c

update facebook URLs to use facebook Graph v2.3

---

README.md
lib/index.js
package.json
test/index.js

Allow environment variables to configure options

---

lib/oauth.js
lib/providers/index.js
lib/providers/reddit.js
package.json
test/providers.js

Additionally enables basic http authentication header as required from reddit for oauth2 to function.

Support Reddit as an OAuth provider

---

README.md
lib/index.js
lib/oauth.js
test/oauth.js

The `forceHttps` option is not sufficient to cover every configuration.  For example the port visible to the user's browser may be different than the port inferred by the Hapi server.  In fact, the host may also be different if there is a load balancer involved.  This PR attempts to restore the flexibility available when bell referenced the Hapi server location setting.

add location setting similar to old hapi server location

---

lib/oauth.js
test/oauth.js

Pass `forceHttps` and `location` to v1 client

Pass `forceHttps` and `location` to v1 client

---

lib/oauth.js
package.json
test/mock.js
test/oauth.js

Closes #90 
This is a bit convoluted but required to keep it backwards compatible with minimal code repeats. In future breaking versions it will be worth getting rid of the `request()` and `get()` methods and just keep the new `resource()` one.

OAuth client resource() endpoint

---

lib/oauth.js
package.json
test/mock.js
test/oauth.js

Rewrite OAuth 1.0 client interface

---

lib/index.js
test/index.js

The default value for `domain` is `null`. However the Joi validation does not accept `null` as valid. Plugins like crumb/yar allow null to be passed in for this. PR is to make it consistent to enable easily using the same variable for `domain` across multiple plugins.

Allow null for domain

---

README.md

Removing port in the constructor and adding call to connection.

Updating Readme examples to work with current version of hapi

---

lib/oauth.js

The code was attempting to access the clientSecret with the wrong variable name.

Fix clientSecret usage

---

lib/oauth.js
test/mock.js
test/oauth.js

This duplicate the fix from [#101](https://github.com/hapijs/bell/pull/101) and includes a proposed test case that would fail without the fix.
The previous suite of tests would complain if the user leaves off the clientSecret or gives it a value of undefined.  But this particular bug happened at the point the clientSecret was assign as part of the query and then converted into a queryString.  Since the wrong variable name was passed the query property client_secret was given a value of undefined.  Then the queryString conversion method changed the undefined value into an empty string which is valid for a clientSecret.

 Fix clientSecret usage and adds test case

---

lib/providers/linkedin.js

Starting from May 12th, 2015, Linkedin's policy has changed: access to members' full profile and contact information has been restricted to Linkedin partners.
https://developer.linkedin.com/blog/posts/2015/developer-program-changes
To keep up to date with these recent changes, the default scope has been updated to information available to every application: users' basic profile and email address.
If one still wants to use the old scope (i.e. your application is part of Linkedin's partnership program), please configure the strategy's scope:
server.auth.strategy('linkedin', 'bell', {
provider: 'linkedin',
password: '',
clientId: '',
clientSecret: '',
scope: ['r_fullprofile', 'r_emailaddress', 'r_contactinfo']
});
I believe that this is a *breaking change*, as the information retrieved by …

Updated LinkedIn's default scope

---

examples/google.js
lib/providers/google.js
test/providers.js

Auth and Token have been updated based on values found in the OpenIDConnect discovery document:
https://accounts.google.com/.well-known/openid-configuration
Scope discussion can be found here:
https://developers.google.com/+/web/api/rest/oauth#plus.login
Goggle discovery doc for the plus service:
https://www.googleapis.com/discovery/v1/apis/plus/v1/rest
Documentation of response body:
https://developers.google.com/+/web/api/rest/latest/people#resource

Updated Google provider so that login uses the recommended Google+ People endpoint

---

examples/google.js

This fixes the google example to use the `location` property not `redirect_uri` as this parameter is inferred from the current URL or the `location` setting if set. See https://github.com/hapijs/bell/blob/master/lib/oauth.js#L156

Fix google example

---

lib/providers/facebook.js
test/oauth.js

Added the fields which are then by default in the profile normalisation.

Add fields to the query

---

examples/facebook.js
lib/providers/facebook.js

Fixes #89 
Adds to #115 to ensure release is backwards compatible

Facebook Provider: Fix expiresIn, add example, backwards compatibility

---

README.md
lib/index.js
lib/oauth.js
test/oauth.js

to be send to auth url // allows runtime changing query params // fixes #125
we can discuss naming ;)

added allowRuntimeProviderParams to allow runtime query params 

---

Providers.md
examples/meetup.js
lib/providers/index.js
lib/providers/meetup.js
test/providers/meetup.js

Using login with meetup.com for a project of mine, was implementing it using a custom bell provider, but thought others might be interested in this so I've decided to contribute back to bell. :smile: 
`npm test` results
```
...
meetup
✔ 71) authenticates with mock (12 ms)
...
79 tests complete
Test duration: 960 ms
No global variable leaks detected
Coverage: 100.00%
Linting results: No issues
```

Meetup.com Provider

---

API.md
README.md
lib/oauth.js
test/oauth.js

Today I've spent most of my morning digging around the Hapi internals to find why the state cookie was being destroyed, only to find that it was because I'm developing locally using http, but had not set `isSecure: false` in the options.
The issue is that the error about the cookie not being set at [line 77](https://github.com/hapijs/bell#/L77) isn't too helpful.  Took me into Hapi's own request internals because I was seeing on the outgoing request when I did console.log
```
{ 'bell-twitter':
{ name: 'bell-twitter',
value:
{ token: '<token>',
secret: '<secret>',
query: {} } } }
Debug: internal, implementation, error
TypeError: Cannot read property 'cookies' of undefined
at [object Object].internals.Request.internals.Request._execute.internals.Request._lifecycle.internals.Request._invoke.i …
```

Add error if using non-https server when isSecure is set to true

---

API.md
lib/index.js
lib/oauth.js
test/oauth.js

There are some cases when I want to use bell with OAuth scopes that don't include the profile. For example, I'm using the Google Calendar scope, but not the profile scope, so bell wouldn't be able to fetch the profile. This lets the user skip fetching the profile from their provider config, without having to write a new provider with their blank `profile` function.

skipProfile option

---

API.md
Providers.md
lib/providers/auth0.js
lib/providers/index.js
test/providers/auth0.js

Wanting to use Auth0 with bell so I implemented it as a provider. If this could eventually get merged I can write the tests and add it to docs.
Some references:
* https://auth0.com/docs/protocols#oauth-server-side
* https://auth0.com/docs/auth-api
* https://auth0.com/docs/user-profile/normalized
Thanks!

Add Auth0 provider

---

API.md
lib/index.js
lib/oauth.js
test/oauth.js

I'd like to add additional data to the OAuth state parameter. So far bell creates its state parameter by using an arbitrary nonce and there is no way for intercepting or extending the state.
This is useful due to restrictions on OAuth redirect_uri. Each provider has its own rules for the callback uri. E.g. OneDrive only allows urls from within a master domain. This makes development and testing complicated: I need to change allowed redirect uris for this. Also if you like to host multiple instances of an application on different domains, things get complicated - at least, or cannot be solved (OneDrive example). By passing additional data a central redirect location can decide where to forward a successful authorization request. Use the bell 'location' setting for this and provide your …

Allow passing additional state

---

Providers.md
lib/providers/bitbucket.js
test/providers/bitbucket.js

Not sure why this wasn't picked up in the PR, but there are a couple issues.
1. It seems `profile.uuid` should be used instead of `profile.username` for `credentials.profile.id`.
2. The style in which this was written differs from the other providers we have.
I've gone ahead and fixed both issues in this PR.

Bitbucket incorrect id and styling inconsistency.

---

Providers.md

Add description in provider docs to show how to authenticate Slack for a specific team

added docs for Slack team auth

---

API.md
Providers.md
examples/office365.js
lib/providers/index.js
lib/providers/office365.js
package.json
test/providers/office365.js

This doesn't yet pass all the tests - `npm test` returns with 
...
Edit: Should be all set, first experience with Lab, and it took me a bit to track down the problems, but glad I did.

Office365 provider

---

Providers.md
lib/providers/index.js
lib/providers/wordpress.js
package.json
test/providers/wordpress.js

WordPress Provider

---

.eslintrc
lib/oauth.js
test/oauth.js

Based on #206 and Fixes #191.
Could I get someone to review this?
The crux of the issue is that Safari, due to CORS and the way Facebook sometimes does the redirect, it will not send the state cookie along. So, when we see no token (usually happens during development due to bad settings), we attempt to refresh the page using the meta keyword (not using javascript) and this ensures that Safari sends us the cookie.
We attempt to not have infinite loops with adding the refresh query parameter.

Fix Safari CORS with Facebook & potentially other providers

---

API.md
Providers.md
README.md
lib/providers/index.js
lib/providers/pinterest.js
test/providers/pinterest.js

Hi, 
I'm working on a project that needs to support Pinterest for authentication.
Since my team is using Bell to manage other social networks, I thought it would be nice to write a provider for Pinterest on my own and than submit it to you, so other people can use it.
I also wrote the test (100% coverage) and the documentation about it.
If you would like any further information, please don't hesitate to contact me.
Bye
Antonio

Add Pinterest provider

---

lib/oauth.js
package.json

This might benefit from some tests confirming that all these methods return a node `req` object. This is needed in case you want to `req.abort()` etc. I don't have the time to add tests but this is probably worth merging and adding a new issue for the missing tests...

Consistently return node req object in oauth v1 client. Closes #215

---

lib/oauth.js
test/oauth.js

@ldesplat After the fix for https://github.com/hapijs/bell/pull/208 it looks like at least on chrome it's possible to simulate an infinite redirect. It's triggered by unbalanced quotes used in the markup which make the current browser location be the redirect url without the refresh param. I've updated the markup to be similar to the [W3 Example](https://www.w3.org/TR/WCAG20-TECHS/H76.html#H76-examples) to avoid the infinite redirect

Fix markup to quote URL correctly to avoid infinite redirect

---

API.md
Providers.md
lib/providers/twitter.js
test/providers/twitter.js

Introduces ``getMethod`` option to Twitter provider in order to allow using different methods from its rest API.

getMethod option

---

API.md
Providers.md
lib/providers/fitbit.js
lib/providers/index.js
package.json
test/providers/fitbit.js

Fitbit uses Bell in their third-party integrations with Strava and IFTTT, and so we thought this would be a useful resource. Feel free to reach out if you have any questions or changes :) Thank you!

Fitbit provider

---

lib/providers/linkedin.js

Fixes email address field in LinkedIn.  Raw profile output:
raw:
{
emailAddress: 'kamronsEmailHere',
firstName: 'Kamron',
id: 'NUMBER_HERE',
lastName: 'Batman',
}

[Fix] Fixes email address field in LinkedIn

---

API.md
Providers.md
README.md
lib/providers/googleplus.js
lib/providers/index.js
test/providers/googleplus.js

Issue is at: #228
See #229 for previous discussion.

Separate Google into two providers. #228

---

API.md
lib/index.js
lib/oauth.js
test/oauth.js

This allows provideParams to be a method which, when invoked with the request object, returns query parameters to add to the request.
For certain OAuth servers which include additional metadata in the request (for us: Discord's OAuth system) it's sometimes desirable to be able to selectively request features depending on configuration in the auth request.

Allow providerParams to be a method invoked with the request

---

Providers.md
lib/providers/twitter.js
test/providers/twitter.js

I was trying to retrieve the email of Twitter users and found it on [this API route](https://dev.twitter.com/rest/reference/get/account/verify_credentials). However, fetching the email from this route requires an additional GET parameter. This PR allows for additional parameters to that extended profile call.
Questions I have:
1. When writing the test for this option, I couldn't find a way in the Mock'd Twitter endpoint to verify if there were actual GET parameters passed to that route. Is this something that's testable?
2. Should dynamic GET parameters (via a function in the config) be allowed? In my use case, I only needed to add `"include_email": "true"`, but other parameters might be dependent on the authenticated user's information.
Thanks!

Twitter additional GET parameters on extended profile request

---

lib/oauth.js

Some oauth providers (specifically AT&T) return their JSON payloads with lots of leading whitespace, which fails the current test of `payload[0] === '{'` and causes the response from `get` to be passed through `Querystring.parse` instead.
This PR is an attempt to allow for situations like this, and still properly catch these payloads as JSON.
I tried looking through the tests to see where I could add a case to ensure this works but didn't see anywhere that stood out to me. I'm more than happy to attempt that if given a little more direction on this.

allow for leading whitespace in JSON

---

Providers.md
README.md
examples/discord.js
lib/providers/discord.js
lib/providers/index.js
test/providers/discord.js

I added discord ([https://discordapp.com/developers/docs/topics/oauth2](https://discordapp.com/developers/docs/topics/oauth2)) as a new provider for bell. I'm working on a project which needs the ability to login with discord.
The tests are working & the code coverage is still 100%, here's a pastebin for the test results: [http://pastebin.com/CA7GnBdV](http://pastebin.com/CA7GnBdV).
The documentation of the provider was added to the `Providers.md` file as well.
Let me know if there's something missing.

Add discord as a new provider

---

lib/index.js

Resolves #264 in a non-breaking manner.
Had to turn off code coverage for the Hapi 13 support, due to multiple reasons:
1. Don't want to run code coverage using hapi 13
2. Hapi 14 and up, don't error on server.state with cookie passwords less than 32 characters like Hapi 13 did so I don't know how to force an error here either.
3. The way Hapi is implemented makes it hard to stub out the server.state method to force those scenarios.
Plan is to remove this code in next breaking release and stop support for Hapi 13 at that time.

Set isSameSite to false and add code to support Hapi 13.5+

---

Providers.md
lib/providers/azuread.js
lib/providers/index.js
test/providers/azuread.js

Signed off by: Sudheesh Singanamalla <susingan@microsoft.com>

Fixes #266 Implements azure active directory as bell azuread module

---

README.md

I originally missed the `examples` directory and thought it'd be nice to link to in the README.

Add link to all examples

---

Providers.md
lib/providers/azuread.js
test/providers/azuread.js

Support the email field, when `userPrincipalName` is not available.
From the Azure Active Directory graph API documentation about `userPrincipalName` (`upn`):
> This property is required when a work or school account is created; it is optional for local accounts. 
https://msdn.microsoft.com/en-us/library/azure/ad/graph/api/entity-and-complex-type-reference#contact-entity
When `upn` is not available, `profile.email` stores the email, so fall back on this value.
Have tested on an account created from live.com, where the `email` value exists there, but not `upn`.

AzureAD: Support email, when userPrincipalName (upn) is not available

---

lib/oauth.js
test/providers/auth0.js

OpenId Connect providers return an ID token in the `id_token` property of
their `token` response, e.g. `auth0` with `scope: ['openid']`. This
change caters for any scenario requiring unexpected properties from the
`token` response by exposing the full `token` payload as
`request.auth.artifacts`.

Fixes #261 expose OAUTH2 token response as request.auth.artifacts

---

Providers.md
lib/providers/index.js
lib/providers/spotify.js
test/providers/spotify.js

added spotify

---

lib/providers/okta.js

The overwhelming majority of use cases for Okta will need profile information. It was an oversight on my part to not add this originally here: https://github.com/hapijs/bell/pull/299.

Add `'profile'` to list of default scopes for Okta

---

Providers.md
README.md
lib/providers/index.js
lib/providers/stripe.js
test/providers/stripe.js

Time to make some $$$, yo.
This PR adds [Stripe](https://stripe.com), one of the most popular payment platforms, as a new provider. With this, we can use [Stripe Connect](https://stripe.com/connect) to help sellers sign up or log in to our platform and earn a living.
Stripe OAuth docs: https://stripe.com/docs/connect/oauth-reference

Add Stripe as a new provider

---

Providers.md
README.md
lib/providers/index.js
lib/providers/mixer.js
test/providers/mixer.js

Tested this last night and it worked fine, apologizes if there's anything different in the test file. Haven't created many of those myself.

Add Mixer as a new provider

---

Providers.md
lib/providers/facebook.js
test/providers/facebook.js

This commit adds a new option (and the first) configuration option
to the Facebook provider: `fields`, which allows to request
additional profile fields if needed.
This should be a non-breaking change, as the `fields` option has a
default value.
Fix #297

Add `fields` option to Facebook provider

---

API.md
lib/index.js
lib/oauth.js
test/oauth.js

Addresses some of the need described in https://github.com/hapijs/bell/issues/184.
Specifically, I need this to avoid appending the request.path to the redirect URI, because I'm working with an OAuth2 provider that forbids any path (even a trailing slash).

Allowing the location option to be a function

---

API.md
lib/index.js
lib/oauth.js
lib/providers/dropbox-v2.js
lib/providers/index.js
test/oauth.js
test/providers/dropbox-v2.js

The existing Dropbox provider uses Dropbox API V1 which has been deprecated in April 2016. New API V2 uses "RPC" style calls (i.e. POST) for requesting user account information. So far all providers are requesting account information by GET calls. There is a new provider config option now ("providerMethod") which can be set to 'post' in order to get account information by POST request (defaults to 'get').
[https://www.dropbox.com/developers/documentation/http/documentation#users-get_current_account](https://www.dropbox.com/developers/documentation/http/documentation#users-get_current_account)

New dropbox-v2 provider which uses Dropbox V2 API

---

README.md

I tried to use a similar writing style to the notice on https://hapijs.com/tutorials

provide a notice that Bell currently supports Hapi v16, not v17

---

lib/providers/facebook.js
test/providers/facebook.js

Updated test Case for facebook but when running tests it shows error in other files.
This is my error:
```
Coverage: 92.13% (124/1575)
lib/oauth.js missing coverage on line(s): 312, 313, 316, 346
lib/providers/arcgisonline.js missing coverage on line(s): 21, 24, 26, 28
lib/providers/auth0.js missing coverage on line(s): 29, 30
lib/providers/azuread.js missing coverage on line(s): 24, 26, 29
lib/providers/bitbucket.js missing coverage on line(s): 19, 21
lib/providers/digitalocean.js missing coverage on line(s): 23, 24, 26
lib/providers/discord.js missing coverage on line(s): 20, 22
lib/providers/dropbox-v2.js missing coverage on line(s): 21, 22
lib/providers/dropbox.js missing coverage on line(s): 20, 21
lib/providers/fitbit.js missing coverage on line(s): 21, 23 …
```

facebook picture field added to get profile picture

---

lib/providers/facebook.js
test/providers/facebook.js

Hi @AdriVanHoudt ,
Finally after changing the picture fields' value from just the url to a object i am able to pass the tests.
Sorry for bothering you again, but this time it seems to be working fine.
Thank you. :)

Picture object included in the profile object for facebook oauth

---

lib/index.js

This was set to `false` a long time ago, mainly due to a Chrome bug that prevented OAuth from working with `Strict` mode (see https://github.com/aspnet/Security/issues/1231 for a good explanation of the infinite login loop).
That Chrome bug has since been fixed.
I have thoroughly tested that `Strict` works correctly now, across browsers. Chrome was the only browser to ever have an issue with this, though.

Set SameSite=Strict for improved security

---

lib/providers/auth0.js
test/providers/auth0.js

This tiny change ensures that Auth0 won't break for bell users when Auth0 replaces their legacy user profile endpoint with an OIDC compliant one.
Note that this change does not require any action on the part of the user and it is backwards compatible because Auth0 is already returning `profile.sub` in addition to the old `profile.user_id` in order to make it easier to transition.

Use OIDC compliant profile from Auth0

---

API.md

looks like this wasnt updated when the signature changed for hapi v17. i spent a bit more time figuring this out while upgrading an app to hapi v17 because the docs weren't up to date. since this change aligns well with other hapi v17 updates, i expected it to be similar to this, but had to dive into the source to confirm the expectation.
this was somewhat awkward to adjust and still stay in line with the conventions of the rest of the document, so i'm open to adjustments if there are thoughts that would make it more consistent.

Update bell.simulate() docs to align with hapi 17 updates

---

lib/providers/auth0.js

This is a bugfix for Auth0’s “Last time you logged in with” flow. Previously, if a user clicked on their existing session instead of the "Not your account?" link, then `request.auth.credentials` would not contain the user's profile information. That was very confusing because `bell` normally provides the full profile. The bug was a hard one to track down, since it only happens to users who visit the login page while they are already logged in.
This PR fixes the problem by explicitly requesting all of the scopes necessary for `bell` to function as intended. Auth0's APIs behave themselves when you do this. 😄

Ensure Auth0 profile is availabe in all cases

---

Providers.md
lib/providers/facebook.js
test/oauth.js
test/providers/facebook.js

- Upgrade FB version from `2.9` to `3.1`
- Add the ability to update Facebook login scope

FB custom scope + upgrade api version

---

README.md
lib/providers/vk.js
test/providers/vk.js

Update response data from vk (move 'uid' to 'id')
And add custom config 'fields'

V9.3.2 add config 'fields' to vk provider

---

lib/providers/stripe.js
test/providers/stripe.js

"Express", as Stripe calls it, is a new flow for setting up Stripe Connect accounts. It is more friendly to users and looks better. Stripe is recommending using this going forward, though the older "Standard" account setup is still available.
I'm not sure what the semver policy is here for changes to providers, but this should probably be considered a breaking change for Stripe users, to be safe, since there are some slight differences when interacting with Stripe Express accounts via their API. There are minimal changes for `bell` users, though.

Use Stripe Express

---

API.md
lib/index.js

Fixes #395 by allowing customization of the `isSameSite` param.

Allow isSameSite customization

---

lib/oauth.js
package.json
test/index.js
test/oauth.js

This PR includes two fixes related to [hapi 18](https://github.com/hapijs/hapi/issues/3871):
1. Many tests broke because hapi now strips the default port from `request.info.host` (a side effect of using the WHATWG URL API) – causing lots of assertions to fail. I decided to use a non-default port in the tests instead of removing the default port from the assertions. This verifies that port info is still propagated correctly.
2. `request.url.query` is no longer available. I’ve changed it to `request.query` which works for hapi 18 and older versions. (I’ve tested it with hapi 17 and 18). This fixes #394.

Add support for hapi 18

---

lib/providers/linkedin.js
test/mock.js
test/providers/linkedin.js

- Switched to use the new `liteprofile` scope
- Grabs email from new dedicated endpoint
Will be testing this in another app tomorrow just to make sure I didn't miss anything.
Note: I had to update mock to support overriding both the endpoints - not sure if thats the best way...
Resolves #390

Update LinkedIn to use new lite profile

---

examples/okta.js
lib/index.js
test/index.js

This PR fixes a problem I am having during my upgrade to hapi 18 and the new `@hapi` scoped package names.
My [hapi-doorkeeper](https://github.com/sholladay/hapi-doorkeeper) plugin [depends on](https://github.com/sholladay/hapi-doorkeeper/blob/master/index.js#L123-L126) `@hapi/cookie` and `@hapi/bell`. However, the `@hapi/bell` dependency was failing with this error when starting the server...
```js
Error: Plugin hapi-doorkeeper missing dependency @hapi/bell
```
It took a while to figure out that it's because `@hapi/bell` has a hardcoded plugin name that is different from the package name, which is inconsistent with `@hapi/cookie` and others. I've fixed this to be consistent with other plugins, in that the `@hapi/` prefix is part of the plugin name.
This is technically a breaking change. …

Use actual package name for plugin name

---

API.md

Adding missing documentation for `request.auth` schema for all supported protocols and authentication configurations.
**Note:** Wasn't sure if  `request.auth.credentials.profile` required documentation as it was already documented on each provider and the property name is not mandatory (a custom provider might use a different name)

Add authentication information documentation

---

API.md
examples/github.js
examples/okta.js
examples/twitch.js

Some authentication providers examples included a verification over the `request.auth.isAuthenticated` property even when the default authentication mode is set to `required` when the handler would have never been called.
Not sure if that was intended, but confused me a little bit since my handler was never being called on authentication errors.

[master] Update documentation to use the correct authentication mode

---

Providers.md
lib/providers/okta.js
test/providers/okta.js

[Okta custom authorization servers](https://support.okta.com/help/s/article/Difference-Between-Okta-as-An-Authorization-Server-vs-Custom-Authorization-Server) require the addition of an alphanumeric ID after the `/oauth2` URL segment which cannot be done using just the base `uri` option. I opted to implemented this change this way as to not require a major version bump, even though it might be cleaner to just drop the `/oauth2` part of the URL that Bell adds and force people to move it into their `uri` option.

Support Okta custom authorization server

---

API.md
lib/index.js
lib/oauth.js
test/oauth.js

Add support for providing clientSecret as a function

---

Providers.md
examples/discord.js
lib/providers/discord.js
test/providers/discord.js

Discord said they would drop support for the `discordapp.com` domain sometime soon in favor of the `discord.com` domain.  This updates the links to avoid it from breaking users' code out of the blue.

Discord provider: update to use new links

---

.github/workflows/ci-plugin.yml
LICENSE.md
lib/index.js
lib/oauth.js
lib/providers/azure-legacy.js
lib/providers/azure.js
lib/providers/cognito.js
lib/providers/digitalocean.js
lib/providers/discord.js
lib/providers/facebook.js
lib/providers/foursquare.js
lib/providers/github.js
lib/providers/gitlab.js
lib/providers/instagram.js
lib/providers/linkedin.js
lib/providers/live.js
lib/providers/okta.js
lib/providers/phabricator.js
lib/providers/pingfed.js
lib/providers/salesforce.js
lib/providers/spotify.js
lib/providers/trakt.js
lib/providers/twitter.js
lib/providers/vk.js
lib/providers/yahoo.js
package.json
test/esm.js
test/mock.js

- Support and test on hapi v21, drop support for hapi v19 and below.
- Support and test on node v18, drop support for node v12 and below.
- Test ESM support.
- Utilize some node v14+ new syntax.
If this looks good, this will go out as bell v13.

Support hapi v21 and node v18, drop hapi v19 and node v12, test ESM support
